config/routes.rb
Rails.application.routes.draw do
  resources :seat_classes
  resources :seats
  resources :flights
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
    has_many :seats, dependent: :destroy
end

app/models/seat.rb
class Seat < ApplicationRecord
    belongs_to :flight
    belongs_to :seat_class

    validate :check_capacity
    validate :check_baggage

    private
    def check_capacity
        seats = Seat.where(flight_id: flight_id).length
        capacity = Flight.find(flight_id).capacity

        if seats >= capacity then
            errors.add(:flight_id, "The flight is full")
        end
    end
    def check_baggage
        seats = Seat.where(flight_id: flight_id)
        
        sum_baggage = 0

        #accumulator
        seats.each do |s|
            sum_baggage += s.baggage.to_f
        end

        baggage_capacity = Flight.find(flight_id).baggage_allowance

        if sum_baggage + baggage > baggage_capacity then
            errors.add(:baggage, "The baggage must not exceed by " + (-1 *( baggage_capacity - sum_baggage - baggage )).to_s)
        end
    end
end

app/models/seat_class.rb
class SeatClass < ApplicationRecord
    has_many :seat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    @open_flights = []
    @closed_flights = []

    @flights.each do |f|
      if f.seats.length >= f.capacity
        @closed_flights.append(f)
      else
        @open_flights.append(f)
      end
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:departure, :arrival, :destination, :baggage_allowance, :capacity)
    end
end

app/controllers/seat_classes_controller.rb
class SeatClassesController < ApplicationController
  before_action :set_seat_class, only: [:show, :edit, :update, :destroy]

  # GET /seat_classes
  # GET /seat_classes.json
  def index
    @seat_classes = SeatClass.all
  end

  # GET /seat_classes/1
  # GET /seat_classes/1.json
  def show
  end

  # GET /seat_classes/new
  def new
    @seat_class = SeatClass.new
  end

  # GET /seat_classes/1/edit
  def edit
  end

  # POST /seat_classes
  # POST /seat_classes.json
  def create
    @seat_class = SeatClass.new(seat_class_params)

    respond_to do |format|
      if @seat_class.save
        format.html { redirect_to @seat_class, notice: 'Seat class was successfully created.' }
        format.json { render :show, status: :created, location: @seat_class }
      else
        format.html { render :new }
        format.json { render json: @seat_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seat_classes/1
  # PATCH/PUT /seat_classes/1.json
  def update
    respond_to do |format|
      if @seat_class.update(seat_class_params)
        format.html { redirect_to @seat_class, notice: 'Seat class was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat_class }
      else
        format.html { render :edit }
        format.json { render json: @seat_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seat_classes/1
  # DELETE /seat_classes/1.json
  def destroy
    @seat_class.destroy
    respond_to do |format|
      format.html { redirect_to seat_classes_url, notice: 'Seat class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat_class
      @seat_class = SeatClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_class_params
      params.require(:seat_class).permit(:class_name, :price, :food_service, :seat_type, :leg_room)
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all.order(flight_id: :asc)
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url, notice: 'Seat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_params
      params.require(:seat).permit(:flight_id, :name, :baggage, :seat_class_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/seat_classes_helper.rb
module SeatClassesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.datetime_select :arrival %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :baggage_allowance %>
    <%= form.text_field :baggage_allowance %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_list_flight.html.erb
<p id="notice"><%= notice %></p>

<h1><%= header %></h1>

<table>
  <thead>
    <tr>
      <th>Departure</th>
      <th>Arrival</th>
      <th>Destination</th>
      <th>Baggage allowance</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% flights.each do |flight| %>
      <tr>
        <td><%= flight.departure %></td>
        <td><%= flight.arrival %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.baggage_allowance %></td>
        <td><%= flight.capacity %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if header != "Closed Flights"  then %>
  <%= link_to 'New Flight', new_flight_path %>
<% end %>

app/views/flights/_seat_form.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :flight_id, :value=> flight_id %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <div>
    <%= form.label "Type of class seat"%>
    <%= form.select :class_seat_id, [["First Class", 1], ["Business Class", 2], ["Economy Plus", 3], ["Economy", 4]], {include_blank: 'Choose Class Seat'}, {id: :class_seat_id} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_seat_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<%= render "list_flight", flights: @open_flights, header: "Open Flights"%>
<%= render "list_flight", flights: @closed_flights, header: "Closed Flights"%>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @flight.arrival %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Baggage Allowance:</strong>
  <%= @flight.baggage_allowance %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @flight.capacity %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

<%= render 'seat_index', seats: @flight.seats %>
<% if @flight.seats.length < @flight.capacity then %>
  <%= render 'seat_form', seat: Seat.new, flight_id: @flight.id %>
<% else %>  
  FLIGHT IS FULL 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoconutAirways</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>

    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seat_classes/_form.html.erb
<%= form_with(model: seat_class, local: true) do |form| %>
  <% if seat_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat_class.errors.count, "error") %> prohibited this seat_class from being saved:</h2>

      <ul>
      <% seat_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class_name %>
    <%= form.text_field :class_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :food_service %>
    <%= form.check_box :food_service %>
  </div>

  <div class="field">
    <%= form.label :seat_type %>
    <%= form.text_field :seat_type %>
  </div>

  <div class="field">
    <%= form.label :leg_room %>
    <%= form.number_field :leg_room %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seat_classes/edit.html.erb
<h1>Editing Seat Class</h1>

<%= render 'form', seat_class: @seat_class %>

<%= link_to 'Show', @seat_class %> |
<%= link_to 'Back', seat_classes_path %>

app/views/seat_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seat Classes</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Price</th>
      <th>Food service</th>
      <th>Seat type</th>
      <th>Leg room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seat_classes.each do |seat_class| %>
      <tr>
        <td><%= seat_class.class_name %></td>
        <td><%= seat_class.price %></td>
        <td><%= seat_class.food_service %></td>
        <td><%= seat_class.seat_type %></td>
        <td><%= seat_class.leg_room %></td>
        <td><%= link_to 'Show', seat_class %></td>
        <td><%= link_to 'Edit', edit_seat_class_path(seat_class) %></td>
        <td><%= link_to 'Destroy', seat_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat Class', new_seat_class_path %>

app/views/seat_classes/new.html.erb
<h1>New Seat Class</h1>

<%= render 'form', seat_class: @seat_class %>

<%= link_to 'Back', seat_classes_path %>

app/views/seat_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class name:</strong>
  <%= @seat_class.class_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @seat_class.price %>
</p>

<p>
  <strong>Food service:</strong>
  <%= @seat_class.food_service %>
</p>

<p>
  <strong>Seat type:</strong>
  <%= @seat_class.seat_type %>
</p>

<p>
  <strong>Leg room:</strong>
  <%= @seat_class.leg_room %>
</p>

<%= link_to 'Edit', edit_seat_class_path(@seat_class) %> |
<%= link_to 'Back', seat_classes_path %>

app/views/seats/_form.html.erb
<%= form_with(model: seat, local: true) do |form| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.number_field :flight_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :baggage %>
    <%= form.text_field :baggage %>
  </div>

  <div>
    <%= form.label "Type of class seat"%>
    <%= form.select :class_seat_id, [["First Class", 1], ["Business Class", 2], ["Economy Plus", 3], ["Economy", 4]], {include_blank: 'Choose Class Seat'}, {id: :class_seat_id} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Name</th>
      <th>Baggage</th>
      <th>Class Seat ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.flight_id %></td>
        <td><%= seat.name %></td>
        <td><%= seat.baggage %></td>
        <td><%= seat.class_seat_id%></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight:</strong>
  <%= @seat.flight_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @seat.name %>
</p>

<p>
  <strong>Baggage:</strong>
  <%= @seat.baggage %>
</p>

<p>
  <strong>Class Seat ID:</strong>
  <%= @seat.class_seat_id %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>